name: Pacman Contributions

on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman contribution graph
        uses: ahmadawais/gh-contribution-grid-snake-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filename: output/pacman-contribution-graph.svg
